"""second migration

Revision ID: 3c69879d0f5e
Revises: 68c0a3125323
Create Date: 2020-02-27 10:09:18.267546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c69879d0f5e'
down_revision = '68c0a3125323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('cash', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=25), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('transact_type', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=25), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('transact_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('shares', sa.NUMERIC(), nullable=False),
    sa.Column('price', sa.NUMERIC(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=250), nullable=False),
    sa.Column('phash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cash', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_table('records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
